// <auto-generated />
using System;
using AuthApi;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace authapi.Migrations
{
    [DbContext(typeof(AuthDbContext))]
    [Migration("20260514120000_AllowReuseOfInactiveLogin")]
    partial class AllowReuseOfInactiveLogin
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("aut")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AuthApi.Models.CommunicationInfo", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .HasColumnType("nvarchar(26)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int>("OwnerType")
                        .HasColumnType("int");

                    b.Property<string>("PlatformUserId")
                        .HasMaxLength(26)
                        .HasColumnType("nvarchar(26)");

                    b.Property<string>("TenantUserId")
                        .HasMaxLength(26)
                        .HasColumnType("nvarchar(26)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PlatformUserId");

                    b.HasIndex("TenantUserId");

                    b.ToTable("CommunicationInfos", "aut", t =>
                        {
                            t.HasCheckConstraint("CK_CommunicationInfos_Target", "\r\n                (CASE WHEN PlatformUserId IS NOT NULL THEN 1 ELSE 0 END)\r\n              + (CASE WHEN TenantUserId IS NOT NULL THEN 1 ELSE 0 END) = 1");
                        });
                });

            modelBuilder.Entity("AuthApi.Models.ContactAddress", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .HasColumnType("nvarchar(26)");

                    b.Property<string>("City")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("CommunicationInfoId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("nvarchar(26)");

                    b.Property<string>("Country")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit");

                    b.Property<string>("Label")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Line1")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Line2")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Notes")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CommunicationInfoId", "IsPrimary");

                    b.ToTable("ContactAddresses", "aut");
                });

            modelBuilder.Entity("AuthApi.Models.ContactPhone", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .HasColumnType("nvarchar(26)");

                    b.Property<string>("CommunicationInfoId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("nvarchar(26)");

                    b.Property<string>("CountryCode")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Extension")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CommunicationInfoId", "IsPrimary");

                    b.ToTable("ContactPhones", "aut");
                });

            modelBuilder.Entity("AuthApi.Models.Credential", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .HasColumnType("nvarchar(26)");

                    b.Property<DateTime?>("AgreementsAcceptedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("AgreementsVersion")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerId")
                        .HasMaxLength(26)
                        .HasColumnType("nvarchar(26)");

                    b.Property<string>("Email")
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("bit");

                    b.Property<int>("OwnerType")
                        .HasColumnType("int");

                    b.Property<DateTime?>("PasswordChangedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PlatformUserId")
                        .HasMaxLength(26)
                        .HasColumnType("nvarchar(26)");

                    b.Property<string>("TenantUserId")
                        .HasMaxLength(26)
                        .HasColumnType("nvarchar(26)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("Login")
                        .IsUnique()
                        .HasFilter("[IsActive] = 1");

                    b.HasIndex("PlatformUserId");

                    b.HasIndex("TenantUserId");

                    b.ToTable("Credentials", "aut", t =>
                        {
                            t.HasCheckConstraint("CK_Credentials_OneOwner", "\r\n                (CASE WHEN PlatformUserId IS NOT NULL THEN 1 ELSE 0 END)\r\n              + (CASE WHEN TenantUserId IS NOT NULL THEN 1 ELSE 0 END)\r\n              + (CASE WHEN CustomerId IS NOT NULL THEN 1 ELSE 0 END) >= 1");
                        });
                });

            modelBuilder.Entity("AuthApi.Models.Customer", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .HasColumnType("nvarchar(26)");

                    b.Property<string>("AddressLine1")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("AddressLine2")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("City")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Country")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Email")
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("FullName")
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("LoyaltyWalletId")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<bool>("MarketingOptIn")
                        .HasColumnType("bit");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("nvarchar(26)");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L);

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("Customers", "aut");
                });

            modelBuilder.Entity("AuthApi.Models.ExternalLogin", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .HasColumnType("nvarchar(26)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("CredentialId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("nvarchar(26)");

                    b.Property<DateTime?>("LastUsedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProfilePictureUrl")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ProviderDisplayName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("ProviderEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("ProviderUserId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("CredentialId");

                    b.HasIndex("Provider", "ProviderUserId")
                        .IsUnique();

                    b.ToTable("ExternalLogins", "aut");
                });

            modelBuilder.Entity("AuthApi.Models.Permission", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Category")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Description")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Icon")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("Scope")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Key");

                    b.ToTable("Permissions", "aut");

                    b.HasData(
                        new
                        {
                            Key = "platform.tenants.manage",
                            Description = "Create, update or disable any tenant instance.",
                            DisplayName = "Manage Tenants",
                            Scope = 0,
                            SortOrder = 0
                        },
                        new
                        {
                            Key = "platform.parameters.manage",
                            Description = "Adjust system-wide configuration and parameter store.",
                            DisplayName = "Manage Global Parameters",
                            Scope = 0,
                            SortOrder = 0
                        },
                        new
                        {
                            Key = "platform.security.manage",
                            Description = "Manage encrypted credentials, connection strings and platform secrets.",
                            DisplayName = "Manage Security Vault",
                            Scope = 0,
                            SortOrder = 0
                        },
                        new
                        {
                            Key = "platform.security.reveal",
                            Description = "Reveal plaintext secrets (restricted to platform owner).",
                            DisplayName = "Reveal Security Secrets",
                            Scope = 0,
                            SortOrder = 0
                        },
                        new
                        {
                            Key = "platform.tcc.manage",
                            Description = "Operate global TCC treasury, rewards and wallet caps.",
                            DisplayName = "Manage TCC Operations",
                            Scope = 0,
                            SortOrder = 0
                        },
                        new
                        {
                            Key = "platform.logs.view",
                            Description = "Inspect logs and audits across tenants.",
                            DisplayName = "View System Logs",
                            Scope = 0,
                            SortOrder = 0
                        },
                        new
                        {
                            Key = "platform.support.impersonate",
                            Description = "Temporarily act on behalf of a tenant user for support.",
                            DisplayName = "Impersonate Tenant User",
                            Scope = 0,
                            SortOrder = 0
                        },
                        new
                        {
                            Key = "platform.support.selenium.run",
                            Description = "Queue, run and manage Selenium runner test catalog, scenarios and flows from the support console.",
                            DisplayName = "Run Selenium Tests",
                            Scope = 0,
                            SortOrder = 0
                        },
                        new
                        {
                            Key = "platform.auth.screens.manage",
                            Description = "Create screens and assign screen access to platform users.",
                            DisplayName = "Manage Screen Access",
                            Scope = 0,
                            SortOrder = 0
                        },
                        new
                        {
                            Key = "platform.auth.users.view",
                            Description = "List platform users for assignment and directory views.",
                            DisplayName = "View Platform Users",
                            Scope = 0,
                            SortOrder = 0
                        },
                        new
                        {
                            Key = "platform.auth.users.manage",
                            Description = "Create platform users, credentials and role assignments.",
                            DisplayName = "Manage Platform Users",
                            Scope = 0,
                            SortOrder = 0
                        },
                        new
                        {
                            Key = "platform.auth.roles.manage",
                            Description = "Create platform roles and assign UI screens.",
                            DisplayName = "Manage Platform Roles",
                            Scope = 0,
                            SortOrder = 0
                        },
                        new
                        {
                            Key = "ops.analytics.view",
                            Description = "Access tenant analytics and KPI reporting in Ops UI.",
                            DisplayName = "View Tenant Analytics",
                            Scope = 0,
                            SortOrder = 0
                        },
                        new
                        {
                            Key = "ops.layouts.manage",
                            Description = "Manage tenant layouts, theming and client app access in Ops UI.",
                            DisplayName = "Manage Tenant Layouts",
                            Scope = 0,
                            SortOrder = 0
                        },
                        new
                        {
                            Key = "ops.ml.configure",
                            Description = "Manage ML definitions, languages and translations in Ops UI.",
                            DisplayName = "Configure ML",
                            Scope = 0,
                            SortOrder = 0
                        },
                        new
                        {
                            Key = "ops.parameters.write",
                            Description = "Create or update platform parameters in Ops UI.",
                            DisplayName = "Manage Parameters",
                            Scope = 0,
                            SortOrder = 0
                        },
                        new
                        {
                            Key = "ops.public-web.manage",
                            Description = "Manage public web content copy and sections in Ops UI.",
                            DisplayName = "Manage Public Web API Content",
                            Scope = 0,
                            SortOrder = 0
                        },
                        new
                        {
                            Key = "ops.roles.manage",
                            Description = "Manage role/screen mappings in Ops UI.",
                            DisplayName = "Manage Ops Roles",
                            Scope = 0,
                            SortOrder = 0
                        },
                        new
                        {
                            Key = "tenant.parameters.manage",
                            Description = "Adjust tenant-scoped configuration and parameter store.",
                            DisplayName = "Manage Tenant Parameters",
                            Scope = 1,
                            SortOrder = 0
                        },
                        new
                        {
                            Key = "tenant.security.manage",
                            Description = "Manage tenant-scoped external API keys and credentials.",
                            DisplayName = "Manage Tenant Secrets",
                            Scope = 1,
                            SortOrder = 0
                        },
                        new
                        {
                            Key = "tenant.layout.manage",
                            Description = "Adjust robot or floor layouts per tenant.",
                            DisplayName = "Manage Layouts",
                            Scope = 1,
                            SortOrder = 0
                        },
                        new
                        {
                            Key = "tenant.robots.manage",
                            Description = "Enroll, configure and monitor robots for tenant.",
                            DisplayName = "Manage Robots",
                            Scope = 1,
                            SortOrder = 0
                        },
                        new
                        {
                            Key = "tenant.reports.view",
                            Description = "Access tenant-specific sales and activity reports.",
                            DisplayName = "View Tenant Reports",
                            Scope = 1,
                            SortOrder = 0
                        },
                        new
                        {
                            Key = "tenant.cash.manage",
                            Description = "Reconcile cashiers, settle cashier sessions.",
                            DisplayName = "Manage Cash Registers",
                            Scope = 1,
                            SortOrder = 0
                        },
                        new
                        {
                            Key = "tenant.accounting.manage",
                            Description = "Control accounting workflows and billing reconciliation.",
                            DisplayName = "Manage Accounting",
                            Scope = 1,
                            SortOrder = 0
                        },
                        new
                        {
                            Key = "tenant.branch.manage",
                            Description = "Onboard or update dealer and branch staff.",
                            DisplayName = "Manage Branch Users",
                            Scope = 1,
                            SortOrder = 0
                        },
                        new
                        {
                            Key = "tenant.setup.track",
                            Description = "Track tenant onboarding and setup checklist progress.",
                            DisplayName = "Track Setup Progress",
                            Scope = 1,
                            SortOrder = 0
                        },
                        new
                        {
                            Key = "tenant.tcc.manage",
                            Description = "Operate tenant-scoped TCC programs and wallets.",
                            DisplayName = "Manage Tenant TCC",
                            Scope = 1,
                            SortOrder = 0
                        },
                        new
                        {
                            Key = "tenant.inventory.view",
                            Description = "View stock levels and inventory items.",
                            DisplayName = "View Inventory",
                            Scope = 1,
                            SortOrder = 0
                        },
                        new
                        {
                            Key = "tenant.inventory.manage",
                            Description = "Add, update or adjust inventory items.",
                            DisplayName = "Manage Inventory",
                            Scope = 1,
                            SortOrder = 0
                        },
                        new
                        {
                            Key = "tenant.menu.view",
                            Description = "View menu items and categories.",
                            DisplayName = "View Menu",
                            Scope = 1,
                            SortOrder = 0
                        },
                        new
                        {
                            Key = "tenant.menu.manage",
                            Description = "Create, update or remove menu items.",
                            DisplayName = "Manage Menu",
                            Scope = 1,
                            SortOrder = 0
                        },
                        new
                        {
                            Key = "tenant.orders.view",
                            Description = "View order history and details.",
                            DisplayName = "View Orders",
                            Scope = 1,
                            SortOrder = 0
                        },
                        new
                        {
                            Key = "tenant.orders.manage",
                            Description = "Update order status and process refunds.",
                            DisplayName = "Manage Orders",
                            Scope = 1,
                            SortOrder = 0
                        },
                        new
                        {
                            Key = "tenant.pos.operate",
                            Description = "Use point of sale for transactions.",
                            DisplayName = "Operate POS",
                            Scope = 1,
                            SortOrder = 0
                        },
                        new
                        {
                            Key = "tenant.users.view",
                            Description = "View tenant staff and their roles.",
                            DisplayName = "View Tenant Users",
                            Scope = 1,
                            SortOrder = 0
                        },
                        new
                        {
                            Key = "tenant.users.manage",
                            Description = "Create or update tenant staff accounts.",
                            DisplayName = "Manage Tenant Users",
                            Scope = 1,
                            SortOrder = 0
                        },
                        new
                        {
                            Key = "tenant.recipes.view",
                            Description = "View recipe definitions.",
                            DisplayName = "View Recipes",
                            Scope = 1,
                            SortOrder = 0
                        },
                        new
                        {
                            Key = "tenant.recipes.manage",
                            Description = "Create or update recipes.",
                            DisplayName = "Manage Recipes",
                            Scope = 1,
                            SortOrder = 0
                        },
                        new
                        {
                            Key = "tenant.customers.view",
                            Description = "View customer list and profiles.",
                            DisplayName = "View Customers",
                            Scope = 1,
                            SortOrder = 0
                        },
                        new
                        {
                            Key = "tenant.customers.manage",
                            Description = "Edit customer profiles and manage customer data.",
                            DisplayName = "Manage Customers",
                            Scope = 1,
                            SortOrder = 0
                        },
                        new
                        {
                            Key = "tenant.notifications.templates.view",
                            Description = "View tenant-scoped content and notification template definitions.",
                            DisplayName = "View Content Templates",
                            Scope = 1,
                            SortOrder = 0
                        },
                        new
                        {
                            Key = "tenant.notifications.templates.manage",
                            Description = "Create and update tenant-scoped content and notification templates.",
                            DisplayName = "Manage Content Templates",
                            Scope = 1,
                            SortOrder = 0
                        },
                        new
                        {
                            Key = "tenant.notifications.templates.publish",
                            Description = "Publish or archive tenant-scoped content and notification templates.",
                            DisplayName = "Publish Content Templates",
                            Scope = 1,
                            SortOrder = 0
                        },
                        new
                        {
                            Key = "tenant.notifications.templates.media.manage",
                            Description = "Upload and manage template media assets such as email images.",
                            DisplayName = "Manage Template Media",
                            Scope = 1,
                            SortOrder = 0
                        },
                        new
                        {
                            Key = "tenant.tables.view",
                            Description = "View table layout and status.",
                            DisplayName = "View Tables",
                            Scope = 1,
                            SortOrder = 0
                        },
                        new
                        {
                            Key = "tenant.tables.manage",
                            Description = "Configure table layout and assignments.",
                            DisplayName = "Manage Tables",
                            Scope = 1,
                            SortOrder = 0
                        },
                        new
                        {
                            Key = "tenant.vision.edge.view",
                            Description = "View camera panels and occupancy streams for branch edge devices.",
                            DisplayName = "View Vision Edge",
                            Scope = 1,
                            SortOrder = 0
                        },
                        new
                        {
                            Key = "tenant.vision.edge.manage",
                            Description = "Configure edge connection, camera list and stream method.",
                            DisplayName = "Manage Vision Edge",
                            Scope = 1,
                            SortOrder = 0
                        });
                });

            modelBuilder.Entity("AuthApi.Models.PlatformUser", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .HasColumnType("nvarchar(26)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[IsActive] = 1");

                    b.ToTable("PlatformUsers", "aut");
                });

            modelBuilder.Entity("AuthApi.Models.RefreshToken", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .HasColumnType("nvarchar(26)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CredentialId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("nvarchar(26)");

                    b.Property<DateTime>("Expires")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ProcessedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Revoked")
                        .HasColumnType("bit");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CredentialId");

                    b.ToTable("RefreshTokens", "aut");
                });

            modelBuilder.Entity("AuthApi.Models.Role", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .HasColumnType("nvarchar(26)");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ParentRoleId")
                        .HasMaxLength(26)
                        .HasColumnType("nvarchar(26)");

                    b.Property<int>("Scope")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("ParentRoleId");

                    b.ToTable("Roles", "aut");
                });

            modelBuilder.Entity("AuthApi.Models.RolePermission", b =>
                {
                    b.Property<string>("RoleId")
                        .HasMaxLength(26)
                        .HasColumnType("nvarchar(26)");

                    b.Property<string>("PermissionKey")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("RoleId", "PermissionKey");

                    b.HasIndex("PermissionKey");

                    b.ToTable("RolePermissions", "aut");
                });

            modelBuilder.Entity("AuthApi.Models.Screen", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .HasColumnType("nvarchar(26)");

                    b.Property<string>("AppCode")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Description")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("Group")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Icon")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<bool>("IsSystem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Path")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("RequiredPermissionsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ScreenKey")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.HasKey("Id");

                    b.HasIndex("AppCode", "ScreenKey")
                        .IsUnique();

                    b.ToTable("Screens", "aut");
                });

            modelBuilder.Entity("AuthApi.Models.ScreenRole", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .HasColumnType("nvarchar(26)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("nvarchar(26)");

                    b.Property<string>("ScreenId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("nvarchar(26)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("ScreenId", "RoleId");

                    b.ToTable("ScreenRoles", "aut");
                });

            modelBuilder.Entity("AuthApi.Models.ScreenUser", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .HasColumnType("nvarchar(26)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<DateTime?>("ExpiresAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("PlatformUserId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("nvarchar(26)");

                    b.Property<string>("ScreenId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("nvarchar(26)");

                    b.Property<string>("TenantId")
                        .HasMaxLength(26)
                        .HasColumnType("nvarchar(26)");

                    b.HasKey("Id");

                    b.HasIndex("PlatformUserId");

                    b.HasIndex("ScreenId", "PlatformUserId", "TenantId");

                    b.ToTable("ScreenUsers", "aut");
                });

            modelBuilder.Entity("AuthApi.Models.SystemLog", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .HasColumnType("nvarchar(26)");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("EntityId")
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("EntityType")
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("Metadata")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenantId")
                        .HasMaxLength(26)
                        .HasColumnType("nvarchar(26)");

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("UserId")
                        .HasMaxLength(26)
                        .HasColumnType("nvarchar(26)");

                    b.Property<int>("UserType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("SystemLogs", "aut");
                });

            modelBuilder.Entity("AuthApi.Models.Tenant", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .HasColumnType("nvarchar(26)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("Notes")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("Slug")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Subdomain")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Tenants", "aut");
                });

            modelBuilder.Entity("AuthApi.Models.TenantUser", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .HasColumnType("nvarchar(26)");

                    b.Property<string>("AddressLine1")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("AddressLine2")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("City")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Country")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("Email")
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("LastName")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<bool>("MarketingOptIn")
                        .HasColumnType("bit");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("PositionTitle")
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("nvarchar(26)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("TenantUsers", "aut");
                });

            modelBuilder.Entity("AuthApi.Models.TwoFactorChallenge", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .HasColumnType("nvarchar(26)");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("CredentialId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("nvarchar(26)");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("FailedAttempts")
                        .HasColumnType("int");

                    b.Property<string>("LastError")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Target")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("VerifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CredentialId", "CreatedAtUtc");

                    b.ToTable("TwoFactorChallenges", "aut");
                });

            modelBuilder.Entity("AuthApi.Models.UserRole", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .HasColumnType("nvarchar(26)");

                    b.Property<DateTime>("AssignedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("BranchCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PlatformUserId")
                        .HasMaxLength(26)
                        .HasColumnType("nvarchar(26)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("nvarchar(26)");

                    b.Property<string>("TenantUserId")
                        .HasMaxLength(26)
                        .HasColumnType("nvarchar(26)");

                    b.HasKey("Id");

                    b.HasIndex("PlatformUserId");

                    b.HasIndex("RoleId");

                    b.HasIndex("TenantUserId", "RoleId", "BranchCode")
                        .IsUnique()
                        .HasFilter("TenantUserId IS NOT NULL");

                    b.ToTable("UserRoles", "aut", t =>
                        {
                            t.HasCheckConstraint("CK_UserRoles_Target", "\r\n                (CASE WHEN PlatformUserId IS NOT NULL THEN 1 ELSE 0 END)\r\n              + (CASE WHEN TenantUserId IS NOT NULL THEN 1 ELSE 0 END) = 1");
                        });
                });

            modelBuilder.Entity("AuthApi.Models.UserSession", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .HasColumnType("nvarchar(26)");

                    b.Property<string>("AppId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("CredentialId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("nvarchar(26)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("LastSeenAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("RevokedReason")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.HasKey("Id");

                    b.HasIndex("CredentialId", "AppId", "RevokedAtUtc");

                    b.ToTable("UserSessions", "aut");
                });

            modelBuilder.Entity("Continuo.Persistence.Outbox.OutboxMessage", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .HasColumnType("nvarchar(26)");

                    b.Property<string>("ClientApp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CorrelationId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OccurredOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("OriginService")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Processed")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ProcessedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenantCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenantId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("OutboxMessages", "dbo", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Continuo.Persistence.Parameters.ParameterDefinition", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .HasColumnType("nvarchar(26)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("DataType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)")
                        .HasDefaultValue("string");

                    b.Property<string>("Environment")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasDefaultValue("prod");

                    b.Property<string>("FallbackValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsSensitive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Locale")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Revision")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)")
                        .HasDefaultValue("global");

                    b.Property<string>("Section")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("SiteCode")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("TenantCode")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Module", "Section", "Key", "Environment", "Scope", "TenantCode", "Locale", "SiteCode")
                        .HasDatabaseName("IX_ParameterDefinitions_KeyScope");

                    b.ToTable("ParameterDefinitions", "aut");
                });

            modelBuilder.Entity("AuthApi.Models.CommunicationInfo", b =>
                {
                    b.HasOne("AuthApi.Models.PlatformUser", "PlatformUser")
                        .WithMany()
                        .HasForeignKey("PlatformUserId");

                    b.HasOne("AuthApi.Models.TenantUser", "TenantUser")
                        .WithMany()
                        .HasForeignKey("TenantUserId");

                    b.Navigation("PlatformUser");

                    b.Navigation("TenantUser");
                });

            modelBuilder.Entity("AuthApi.Models.ContactAddress", b =>
                {
                    b.HasOne("AuthApi.Models.CommunicationInfo", "CommunicationInfo")
                        .WithMany("Addresses")
                        .HasForeignKey("CommunicationInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CommunicationInfo");
                });

            modelBuilder.Entity("AuthApi.Models.ContactPhone", b =>
                {
                    b.HasOne("AuthApi.Models.CommunicationInfo", "CommunicationInfo")
                        .WithMany("Phones")
                        .HasForeignKey("CommunicationInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CommunicationInfo");
                });

            modelBuilder.Entity("AuthApi.Models.Credential", b =>
                {
                    b.HasOne("AuthApi.Models.Customer", "Customer")
                        .WithMany("Credentials")
                        .HasForeignKey("CustomerId");

                    b.HasOne("AuthApi.Models.PlatformUser", "PlatformUser")
                        .WithMany("Credentials")
                        .HasForeignKey("PlatformUserId");

                    b.HasOne("AuthApi.Models.TenantUser", "TenantUser")
                        .WithMany("Credentials")
                        .HasForeignKey("TenantUserId");

                    b.Navigation("Customer");

                    b.Navigation("PlatformUser");

                    b.Navigation("TenantUser");
                });

            modelBuilder.Entity("AuthApi.Models.Customer", b =>
                {
                    b.HasOne("AuthApi.Models.Tenant", "Tenant")
                        .WithMany("Customers")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("AuthApi.Models.ExternalLogin", b =>
                {
                    b.HasOne("AuthApi.Models.Credential", "Credential")
                        .WithMany()
                        .HasForeignKey("CredentialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Credential");
                });

            modelBuilder.Entity("AuthApi.Models.RefreshToken", b =>
                {
                    b.HasOne("AuthApi.Models.Credential", "Credential")
                        .WithMany()
                        .HasForeignKey("CredentialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Credential");
                });

            modelBuilder.Entity("AuthApi.Models.Role", b =>
                {
                    b.HasOne("AuthApi.Models.Role", "ParentRole")
                        .WithMany("ChildRoles")
                        .HasForeignKey("ParentRoleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentRole");
                });

            modelBuilder.Entity("AuthApi.Models.RolePermission", b =>
                {
                    b.HasOne("AuthApi.Models.Permission", "Permission")
                        .WithMany("Roles")
                        .HasForeignKey("PermissionKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AuthApi.Models.Role", "Role")
                        .WithMany("Permissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("AuthApi.Models.ScreenRole", b =>
                {
                    b.HasOne("AuthApi.Models.Role", "Role")
                        .WithMany("ScreenAssignments")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AuthApi.Models.Screen", "Screen")
                        .WithMany()
                        .HasForeignKey("ScreenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("Screen");
                });

            modelBuilder.Entity("AuthApi.Models.ScreenUser", b =>
                {
                    b.HasOne("AuthApi.Models.PlatformUser", "PlatformUser")
                        .WithMany()
                        .HasForeignKey("PlatformUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AuthApi.Models.Screen", "Screen")
                        .WithMany()
                        .HasForeignKey("ScreenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlatformUser");

                    b.Navigation("Screen");
                });

            modelBuilder.Entity("AuthApi.Models.TenantUser", b =>
                {
                    b.HasOne("AuthApi.Models.Tenant", "Tenant")
                        .WithMany("Users")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("AuthApi.Models.TwoFactorChallenge", b =>
                {
                    b.HasOne("AuthApi.Models.Credential", "Credential")
                        .WithMany()
                        .HasForeignKey("CredentialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Credential");
                });

            modelBuilder.Entity("AuthApi.Models.UserRole", b =>
                {
                    b.HasOne("AuthApi.Models.PlatformUser", "PlatformUser")
                        .WithMany("Roles")
                        .HasForeignKey("PlatformUserId");

                    b.HasOne("AuthApi.Models.Role", "Role")
                        .WithMany("Members")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AuthApi.Models.TenantUser", "TenantUser")
                        .WithMany("Roles")
                        .HasForeignKey("TenantUserId");

                    b.Navigation("PlatformUser");

                    b.Navigation("Role");

                    b.Navigation("TenantUser");
                });

            modelBuilder.Entity("AuthApi.Models.UserSession", b =>
                {
                    b.HasOne("AuthApi.Models.Credential", "Credential")
                        .WithMany()
                        .HasForeignKey("CredentialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Credential");
                });

            modelBuilder.Entity("AuthApi.Models.CommunicationInfo", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("Phones");
                });

            modelBuilder.Entity("AuthApi.Models.Customer", b =>
                {
                    b.Navigation("Credentials");
                });

            modelBuilder.Entity("AuthApi.Models.Permission", b =>
                {
                    b.Navigation("Roles");
                });

            modelBuilder.Entity("AuthApi.Models.PlatformUser", b =>
                {
                    b.Navigation("Credentials");

                    b.Navigation("Roles");
                });

            modelBuilder.Entity("AuthApi.Models.Role", b =>
                {
                    b.Navigation("ChildRoles");

                    b.Navigation("Members");

                    b.Navigation("Permissions");

                    b.Navigation("ScreenAssignments");
                });

            modelBuilder.Entity("AuthApi.Models.Tenant", b =>
                {
                    b.Navigation("Customers");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("AuthApi.Models.TenantUser", b =>
                {
                    b.Navigation("Credentials");

                    b.Navigation("Roles");
                });
#pragma warning restore 612, 618
        }
    }
}
